#!/bin/sh

set -e

[ $# -eq 0 ] && {
  printf "usage: %s <install_dir>\n" "$(basename $0)"
  exit 1
}

OLDWD="$(pwd)"
DEST="$(realpath $*)"

cd src

[ $(ls holidays|wc -l) -eq 0 ] && {
  printf "\n\n%s/holidays is empty. Did you properly initialize the submodule?" "$(pwd)"
  exit 1
}

rsync -r holidays tick vacation version.py tick_completion requirements.txt protocol.py parser.py "$DEST"

cd "$DEST"

virtualenv -p python3.7 venv
. venv/bin/activate

pip install -r requirements.txt
deactivate

cd "$OLDWD"
